# Generated by Django 3.2.4 on 2021-08-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_Json', models.CharField(default='', max_length=5000)),
                ('payment_method', models.CharField(default='', max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customersaddress')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customers')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
