# Generated by Django 3.2 on 2021-05-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='category',
            new_name='title',
        ),
    ]
