# Generated by Django 3.2 on 2021-05-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.productcategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
