# Generated by Django 3.2 on 2021-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20210511_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
