# Generated by Django 3.2 on 2021-05-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20210517_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='subcategory',
            new_name='category',
        ),
    ]
