# Generated by Django 3.2.4 on 2021-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_ordertacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_Json',
            field=models.JSONField(default='', max_length=5000),
        ),
    ]
