# Generated by Django 3.2.4 on 2021-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20210723_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgst',
            name='gst_in_percentage',
            field=models.CharField(choices=[('1', '0%'), ('2', '3%'), ('3', '5%'), ('4', '12%'), ('5', '18%'), ('6', '28%')], max_length=255),
        ),
    ]
