# Generated by Django 3.2.4 on 2021-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='product_main/images'),
        ),
    ]
