# Generated by Django 3.2.4 on 2021-07-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_productgst_gst_in_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgst',
            old_name='gst_in_percentage',
            new_name='percentage',
        ),
    ]
