# Generated by Django 3.2 on 2021-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_productcategory_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
