# Generated by Django 3.2.4 on 2021-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_rename_gst_in_percentage_productgst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgst',
            name='gst_percentage',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productgst',
            name='percentage',
            field=models.CharField(choices=[(1, '0%'), (2, '3%'), (3, '5%'), (4, '12%'), (5, '18%'), (6, '28%')], max_length=255),
        ),
    ]
