# Generated by Django 3.2 on 2021-05-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_productabout_productdetails_productquestions_producttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
