# Generated by Django 3.2.4 on 2021-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_alter_orders_product_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_Json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
