# Generated by Django 3.2.4 on 2021-07-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20210723_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgst',
            name='percentage',
            field=models.CharField(blank=True, choices=[(1, '0%'), (2, '3%'), (3, '5%'), (4, '12%'), (5, '18%'), (6, '28%')], default='', max_length=255, null=True),
        ),
    ]
