# Generated by Django 3.2.4 on 2021-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20210630_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_l_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
