# Generated by Django 3.2.4 on 2021-07-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_productgst_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgst',
            old_name='hsn_nunber',
            new_name='hsn_number',
        ),
    ]
