# Generated by Django 3.2.4 on 2021-08-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_orders_product_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
