# Generated by Django 3.2.4 on 2021-08-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
