# Generated by Django 3.2.4 on 2021-09-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customersaddress_is_default'),
        ('front', '0008_alter_orders_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=1)),
                ('product', models.CharField(default='', max_length=5000)),
                ('quantity', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customersaddress')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customers')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
