# Generated by Django 3.2.4 on 2021-07-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20210724_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['updated_at']},
        ),
    ]
