# Generated by Django 4.0 on 2021-12-30 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_temporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcat', to='front.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_childsubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productchildcat', to='front.productchildsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsubcat', to='front.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='productabout',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productabout', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productchildsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childcategories', to='front.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productdiscount', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productgst',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgst', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productmedia', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productreviews', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productsizeweight',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsizeweight', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productstockmanage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productstockmanage', to='front.product'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='front.productcategory'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttag', to='front.product'),
        ),
    ]
