# Generated by Django 4.0 on 2021-12-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211223_1831'),
        ('front', '0010_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customersaddress'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='productstockmanage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productstockmanage', to='front.product'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customersaddress'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
    ]
