# Generated by Django 4.0 on 2021-12-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211223_1831'),
        ('front', '0011_alter_orders_address_alter_orders_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersorders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='customersorders',
            name='customersaddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customersaddress'),
        ),
        migrations.AlterField(
            model_name='customersorders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.product'),
        ),
        migrations.AlterField(
            model_name='oderdeliverystatus',
            name='Ordes_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front.customersorders'),
        ),
        migrations.AlterField(
            model_name='oderdeliverystatus',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front.product'),
        ),
        migrations.AlterField(
            model_name='productcouponcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.product'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdiscount', to='front.product'),
        ),
    ]
