# Generated by Django 4.0 on 2022-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_alter_customersorders_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_session',
            name='product_in_pdf',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_session',
            name='video_link',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productchildsubcategory',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productreviewvoting',
            name='reviws_images',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
