# Generated by Django 4.0.2 on 2022-02-04 12:03

from django.db import migrations
import front.compression


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_session',
            name='module',
        ),
        migrations.RemoveField(
            model_name='productcomments',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productcomments',
            name='session',
        ),
        migrations.RemoveField(
            model_name='productcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewed',
            name='customer',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='thumbnail',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Product_Modules',
        ),
        migrations.DeleteModel(
            name='Product_Session',
        ),
        migrations.DeleteModel(
            name='ProductComments',
        ),
        migrations.DeleteModel(
            name='viewed',
        ),
    ]
