# Generated by Django 4.0.2 on 2022-02-04 12:31

from django.db import migrations
import front.compression


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_remove_product_session_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productchildsubcategory',
            name='thumbnail',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productreviewvoting',
            name='reviws_images',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='thumbnail',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
    ]
