# Generated by Django 4.0.2 on 2022-02-08 05:01

from django.db import migrations, models
import django.db.models.deletion
import front.compression


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_adminhod_profile_pic_and_more'),
        ('front', '0015_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_by_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.merchants'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productcat', to='front.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_childsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productchildcat', to='front.productchildsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=front.compression.CompressedImageFieldCat(blank=True, default=None, null=True, quality=90, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_l_desc',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mrp',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_selling_price',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(blank=True, default='', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsubcat', to='front.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='thumbnail',
            field=front.compression.CompressedImageFieldCat(blank=True, default=None, null=True, quality=90, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productchildsubcategory',
            name='thumbnail',
            field=front.compression.CompressedImageFieldCat(blank=True, default=None, null=True, quality=90, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productgst',
            name='percentage',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='thumbnail',
            field=front.compression.CompressedImageFieldCat(blank=True, default=None, null=True, quality=90, upload_to=''),
        ),
    ]
