# Generated by Django 4.0.2 on 2022-02-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_alter_product_added_by_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_number',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
