# Generated by Django 4.0.2 on 2022-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_orders_status_alter_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mrp',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
    ]
