# Generated by Django 4.0.2 on 2022-02-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_orders_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
