# Generated by Django 4.0.2 on 2022-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_product_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderdeliverystatus',
            name='tracker_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
