# Generated by Django 4.0.2 on 2022-03-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_oderdeliverystatus_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderdeliverystatus',
            name='status_msg',
            field=models.CharField(choices=[('Prosesing', 'Prosesing'), ('On the Way', 'On the Way '), ('Delivered', 'Delivered')], default='', max_length=255),
        ),
    ]
