# Generated by Django 4.0.2 on 2022-04-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_alter_oderdeliverystatus_status_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderdeliverystatus',
            name='product',
        ),
        migrations.AddField(
            model_name='oderdeliverystatus',
            name='shipment_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='oderdeliverystatus',
            name='Ordes_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.customersorders'),
        ),
        migrations.AlterField(
            model_name='oderdeliverystatus',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oderdeliverystatus',
            name='status_msg',
            field=models.CharField(blank=True, choices=[('Prosesing', 'Prosesing'), ('On the Way', 'On the Way '), ('Delivered', 'Delivered')], default='', max_length=255, null=True),
        ),
    ]
