# Generated by Django 4.0.2 on 2022-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0024_remove_oderdeliverystatus_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_selling_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
