# Generated by Django 4.0.2 on 2022-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='min_purchased_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
