# Generated by Django 3.2 on 2021-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='is_added_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
