# Generated by Django 3.2.4 on 2021-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersaddress',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
