# Generated by Django 3.2 on 2021-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merchants_is_added_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchants',
            old_name='company_registaer_year',
            new_name='company_register_year',
        ),
        migrations.RemoveField(
            model_name='merchants',
            name='fisrt_name',
        ),
        migrations.RemoveField(
            model_name='merchants',
            name='last_name',
        ),
        migrations.AddField(
            model_name='merchants',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='Merchant/images'),
        ),
        migrations.AddField(
            model_name='merchants',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='state',
            field=models.CharField(blank=True, default='Gujarat', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='website',
            field=models.URLField(blank=True, default='www.google.com', null=True),
        ),
    ]
