# Generated by Django 3.2.4 on 2021-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customersaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='zip_Code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
