# Generated by Django 4.0 on 2022-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211223_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
