# Generated by Django 4.0.2 on 2022-02-04 12:31

from django.db import migrations
import front.compression


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminhod_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='profile_pic',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='profile_pic',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='profile_pic',
            field=front.compression.CompressedImageField(blank=True, default=None, null=True, quality=60, upload_to=''),
        ),
    ]
