# Generated by Django 3.2.4 on 2021-07-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210731_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
    ]
