# Generated by Django 3.2.4 on 2021-08-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customersaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersaddress',
            old_name='is_default',
            new_name='is_active',
        ),
    ]
