# Generated by Django 3.2 on 2021-05-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paytm_payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CURRENCY', models.CharField(max_length=50)),
                ('GATEWAYNAME', models.CharField(max_length=500)),
                ('RESPMSG', models.CharField(max_length=1000)),
                ('BANKNAME', models.CharField(max_length=150)),
                ('PAYMENTMODE', models.CharField(max_length=150)),
                ('RESPCODE', models.CharField(max_length=150)),
                ('TXNID', models.CharField(max_length=500)),
                ('TXNAMOUNT', models.CharField(max_length=150)),
                ('ORDERID', models.CharField(max_length=150)),
                ('STATUS', models.CharField(max_length=500)),
                ('BANKTXNID', models.CharField(max_length=500)),
                ('TXNDATE', models.CharField(max_length=500)),
            ],
        ),
    ]
