from django.urls import path
from .import views

urlpatterns = [
    # path('', views.customer_dashboard,name='customer_dashboard'),
    # path('customer_account_edit', views.customer_account_edit,name='customer_account_edit'),
    # path('customer_account_edit_save', views.customer_account_edit_save,name='customer_account_edit_save'),
    # path('customer_account_edit_basic', views.customer_account_edit_basic,name='customer_account_edit_basic'),
    # path('customer_account_edit_profile', views.customer_account_edit_profile,name='customer_account_edit_profile'),
    # path('customer_billing', views.customer_billing,name='customer_billing'),
    # path('customer_browse_products', views.customer_browse_products,name='customer_browse_products'),
    # path('customer_cart/<slug:slug>', views.customer_cart,name='customer_cart'),
    # path('customer_help_center', views.customer_help_center,name='customer_help_center'),
    # path('customer_invoice/<id>', views.customer_invoice,name='customer_invoice'),
    # path('customer_fail/<id>', views.customer_fail,name='customer_fail'),
    # path('customer_messages', views.customer_messages,name='customer_messages'),
    # path('customer_messages_2', views.customer_messages_2,name='customer_messages_2'),
    # path('customer_my_products', views.customer_my_products,name='customer_my_products'),
    # path('customer_pay/<slug:slug>', views.customer_pay,name='customer_pay'),
    # path('customer_quiz_results', views.customer_quiz_results,name='customer_quiz_results'),
    # path('customer_take_product/<slug:slug>', views.customer_take_product,name='customer_take_product'),
    # path('customer_take_product_session/<product_slug>/<slug>/<sslug>', views.customer_take_product_session,name='customer_take_product_session'),
    # path('customer_take_quiz', views.customer_take_quiz,name='customer_take_quiz'),
    # path('customer_view_product', views.customer_view_product,name='customer_view_product'),
    # path('customer_account_billing_payment_information', views.customer_account_billing_payment_information,name='customer_account_billing_payment_information'),
    # path('customer_account_billing_subscription', views.customer_account_billing_subscription,name='customer_account_billing_subscription'),
    # path('customer_account_billing_upgrade', views.customer_account_billing_upgrade,name='customer_account_billing_upgrade'),
    # path('customer_forum', views.customer_forum,name='customer_forum'),
    # path('customer_forum_ask', views.customer_forum_ask,name='customer_forum_ask'),
    # path('customer_forum_thread', views.customer_forum_thread,name='customer_forum_thread'),
    # path('sessionComment/<product_slug>/<slug>/<sslug>', views.sessionComment,name='sessionComment'),
    # path('sessionComment_view/<product_slug>/<slug>/<sslug>', views.sessionComment_view,name='sessionComment_view'),
    # path('customer_profile', views.customer_profile,name='customer_profile'),
    # path('customer_profile_posts', views.customer_profile_posts,name='customer_profile_posts'),
    # path('customer_logout', views.customer_logout,name='customer_logout'),   
    # path('lms_base', views.lms_base,name='lms_base'),   
    # path('handlerequest', views.handlerequest,name='handlerequest'),   
    # path('modules/<slug>', views.modules,name='modules'),   
    # path('session/<product_slug>/<slug>', views.session,name='session'),   
    # path('session_view/<product_slug>/<slug>/<sslug>', views.session_view,name='session_view'),   
    # path('session_seen/<product_slug>/<slug>/<sslug>', views.session_seen,name='session_seen'),

]