# Generated by Django 4.0.2 on 2022-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_complete_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycost',
            name='cost_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverycost',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='cost_per_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='cost_per_product',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='fixed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'active'), ('Passive', 'passive')], default='passive', max_length=7, null=True),
        ),
    ]
