# Generated by Django 4.0.2 on 2022-02-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_deliverycost_cost_kg_deliverycost_state_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycost',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
